### ISSUE TITLE
File open error when onlys using -l

### ISSUE THREAD

**Issue by handiandi** [handiandi/fileJoker_downloader_cli#2]
When only using -l, it gives error when it tries to updating the file (-f): 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./FilejokerDownloader.py", line 122, in delete_id_from_file
    with open(file, 'r+') as f:
TypeError: invalid file: None
```
A solution should be easy

**Comment by masneg** [comment]
I'm waiting for the solution.
thanks
